# This workflow will do a clean installation of Node.js dependencies, cache/restore them, build the source code, and run tests across different versions of Node.js
# For more information, see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI for Node.js

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: ['14.x', '16.x', '18.x']
     
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: npm install

    - name: Build Docker Image
      run: docker build -t raj456/nodeci:latest .

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Push Docker Image to Docker Hub
      run: docker push raj456/nodeci:latest

    - name: Get SHA Digest
      run: |
        SHA_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' raj456/nodeci:latest)
        echo "SHA Digest: $SHA_DIGEST"
        echo "$SHA_DIGEST" > $GITHUB_WORKSPACE/sha_digest.txt

    - name: debug
      run: |
        ls -al
        pwd
    - name: Run container
      run:  docker build --build-arg MY_VARIABLE="${{ env.MY_VARIABLE }}" -t raj456/nodeci:latest .

     
