name: Publish message to Pub/Sub

on: push # Trigger on push events to any branch

jobs:
  publish-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: auth
        name: Authenticate to Google Cloud Platform
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - id: publish
        name: Publish a message to Pub/Sub
        uses: miraliumre/actions-pubsub@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          topic_name: ${{ secrets.PUBSUB_TOPIC_NAME }}
          message: 'This message was published from a GitHub Actions workflow.'
