name: Publish message to Pub/Sub

on: push # Trigger on push events to any branch

jobs:
  publish-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # - id: auth
      #   name: Authenticate to Google Cloud Platform
      #   uses: 'google-github-actions/auth@v1'
      #   with:
      #     credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Install dependencies
        uses: google-github-actions/setup-gcloud@v1
        with:
          project-id: ${{ secrets.GCP_PROJECT_ID }}
          service-account-key: ${{ secrets.GCP_SA_KEY }}
          install-components: "pubsub"

      - name: Publish message
        run: |
          gcloud pubsub topics publish projects/${{ secrets.GCP_PROJECT_ID }}/topics/${{ secrets.PUBSUB_TOPIC_NAME }} --message="This message was published from a GitHub Actions workflow."

