name: Conditional Workflow

on:
  workflow_dispatch:
    inputs:
      choice:
        description: 'Select an option'
        required: true
        options: ['true', 'false']

jobs:
  conditional_job:
    runs-on: ubuntu-latest
    if: github.event.inputs.choice == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Add your workflow steps here




      - name: test-commands
        run: |
          ls -a
      
   
