name: CI for Node.js

on:
 # push:
 #  branches:
 #      - master
 
   workflow_dispatch:
    inputs:
      run_workflow:
         description: 'Select an option'
         required: true
         type: choice
         options:
           - "true"
           - "false"
           

           

jobs:
  build:
    if: github.event.inputs.run_workflow == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: test
        run: |
          la -a
    #       "Shivang") Message="Pithadiya" ;;
    #       *) Message="Unknown option selected" ;;
    #       esac
    #       echo "$Message"
