name: true-false condition

on:
 # push:
 #  branches:
 #      - master
 
   workflow_dispatch:
    inputs:
      run_workflow:
         description: 'Select an option'
         required: true
         type: choice
         options:
           - 'true'
           - 'false'
           

           

jobs:
  build:
    if: github.event.inputs.run_workflow == 'true'
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: test
        run: |
          la -a
          
